### ISSUE TITLE
Change conditional statement in post.jsx if no posts

### ISSUE THREAD

**Issue by kamodulin** [youngrokkim2017/buddy_app#43]
@youngrokkim2017 Can we change the if else statement in post.jsx if there are no posts? autocomplete would not work without removing it... maybe it could go around post.jsx:250?

https://github.com/youngrokkim2017/buddy_app/blob/dfd27d2fd552b8ef96151943838f9113d876034f/frontend/src/components/post/post.jsx#L250-L267

_Originally posted by @kamodulin in https://github.com/youngrokkim2017/buddy_app/pull/42#issuecomment-647035578_

**Comment by youngrokkim2017** [comment]
Yes, I inserted the ternary for the conditional right before the <PostIndexItem />
